[agl][build] Pass missing arguments to WebAppWayland contructor
Passed default values for new arguments locationHint and displayId,
introduced in newer versions of WebOSOSE WAM.

Since commit 51feeff3666e4407758cc9ba54ca3217ba8be7d3 :
"[open][wayland][webos] Implement locationHint"
the WebAppWayland constructor accepts locationHint as
parameter.

Since commit faf93b21a08888b32bd4c579b3aa013651b6ef98 :
"[open][multi_display] Support multi display for web apps"
the WebAppWayland constructor accepts displayId as parameter.

Fixes compilation error:
src/agl/WebAppWaylandAGL.cpp:21:134: error: no matching function for call to
'WebAppWayland::WebAppWayland(const string&, int, int, int, int, int)'