[agl][build] Remove closeByProcessId method
Deleted from WebAppManagerServiceAGL.

Commit e082c9ca931228846f8890280e92f2f559972fa9 :
"[oe][multi-instance] Support muti-instance for web app which has same
id", removed closeByProcessId from the base class, replacing it by
killApp.

Fixes compilation error:

src/agl/WebAppManagerServiceAGL.h:43:17: error: 'Json::Value
WebAppManagerServiceAGL::closeByProcessId(const Json::Value&)' marked
'override', but does not override