[agl][build] Add empty implementation for pauseApp
Added to WebApplicationManagerAGL.

Commit 837d784bde51d703e13759e0d6a59065f86f95cc :
"[open][lifecycle][keepalive] Add web application pausing" added
pauseApp method in the base class.

@TODO: Add real implementation.

Fixes compilation error:
src/agl/WebAppManagerServiceAGL.cpp:209:69: error: invalid
new-expression of abstract class type 'WebAppManagerServiceAGL':
static WebAppManagerServiceAGL *srv = new WebAppManagerServiceAGL();
because the following virtual functions are pure within 'WebAppManagerServiceAGL':
virtual Json::Value pauseApp(const Json::Value &request) = 0;