[agl][build] Add missing declaration of processCrashed
Declaration was accidentaly deleted during the rebase to
WebOSOSE WAM submissions/43.

Fixes compilation error:
src/core/WebAppManager.cpp:564:6: error: no declaration matches
'bool WebAppManager::processCrashed(std::string, std::string)'