[agl][build] delete extra ');'
It was introduced during the rebase to WebOSOSE WAM submissions/43.

Fixes compilation error:
src/platform/webengine/WebPageBlink.cpp:555:5:
error: expected ',' or ';' before ')' token