[agl][build] Pass empty string as instanceId to onKillApp
Commit e082c9ca931228846f8890280e92f2f559972fa9
"[oe][multi-instance] Support muti-instance for web app which has same id"
introduced support for multi-instance apps introducing the instanceId
concept, that it is now used in a variety of operations.

AGL WAM needs to adapt its code to the new multi-instance paradigma.
Until then, we are calling to WebAppManager::instance()->onKillApp
using an empty instanceId to fix a compilation error.

@TODO: ^

src/agl/WebAppManagerServiceAGL.cpp:494:60: error: no matching function
for call to 'WebAppManager::onKillApp(std::string&)'
WebAppManager::instance()->onKillApp(app_id_event_target_);
src/core/WebAppManager.h:104:10: note: candidate:
bool onKillApp(const std::string& appId, const std::string& instanceId, bool force = false);