[agl][build] Delete unused function
Deleted static function truncateURL in WebAppWayland.
This function is no longer used after rebasing to WEBOSOSE WAM
submissions/43.

Fixes compilation issue:
src/platform/WebAppWayland.cpp:39:20: error:
'std::string truncateURL(const string&)' defined but not used [-=unused-function]
cc1plus: all warnings being treated as errors